
library(rliger)
library(rhdf5)
library(HDF5Array)

# The script of iNMF for diagonal integration, [RNA, ATAC] data type, ATAC needs to be coverted into gene activity score. The output is joint embedding (dimension reduction)
# run commond for iNMF
# Rscript main_iNMF.Rmd  '../../data/dataset_final/D27/rna.h5' '../../data/dataset_final/D27/atac_gas.h5' '../../result/embedding/diagonal integration/D27/iNMF/'

h5_to_matrix <- function(path){
    h5_data <- h5read(path,"matrix") 
    feature <- h5_data$features
    barcode <- h5_data$barcodes
    data <- t(h5_data$data)
    colnames(data) <- as.character(barcode)
    rownames(data) <- as.character(feature)
    return (data)
}

write_h5 <- function(exprs_list, h5file_list) {
  if (length(unique(lapply(exprs_list, rownames))) != 1) {
    stop("rownames of exprs_list are not identical.")
  }
  for (i in seq_along(exprs_list)) {
    if (file.exists(h5file_list[i])) {
      warning("h5file exists! will rewrite it.")
      system(paste("rm", h5file_list[i]))
    }
    h5createFile(h5file_list[i])
    writeHDF5Array(((exprs_list[[i]])), h5file_list[i], name = "data")
    print(h5ls(h5file_list[i]))
  }
}

runLIGER<- function(path_list){
  data <- vector("list", length(path_list))
  for (i in c(1:(num-1))){
    temp <- h5_to_matrix(path_list[[i]])
    #colnames(temp) <- paste0(i, "_", 1:dim(temp)[2])
    colnames(temp) <- paste0(i, "_", colnames(temp))
    data[[i]] <- temp
    names(data)[i] <- as.character(i)
  }
    
  pbmcs = createLiger(data)
  pbmcs = rliger::normalize(pbmcs)
  pbmcs = selectGenes(pbmcs, datasets.use = 1)
  pbmcs = scaleNotCenter(pbmcs)
  
  pbmcs <- runIntegration(pbmcs, k = 20)
  pbmcs = quantile_norm(pbmcs)
  result <- pbmcs@H.norm
  return (result)
}

# read parameters, the input is RNA counts and ATAC gene activity score counts
args <- commandArgs(trailingOnly = TRUE)
num <- length(args)
path_list <- vector("list", num-1)
for (i in c(1:(num-1))){
  path_list[[i]] <- args[i]
}
save_path <- args[num] 
print(path_list)

# begin to run
begin_time <- Sys.time()
result <- runLIGER(path_list)
end_time <- Sys.time()
all_time <- difftime(end_time, begin_time, units="secs")

# save the results
if (!dir.exists(save_path)) {
  dir.create(save_path, recursive = TRUE)
  print("path create")
}
print(dim(result))
print(all_time)
write.csv(rownames(result), paste0(save_path,"barcode.csv"))
write_h5(exprs_list = list(rna = result), 
             h5file_list = c(paste0(save_path,"embedding.h5")))
