library(rhdf5)
library(MOFA2)
library(reshape2)
library(HDF5Array)
source("util.R")

# The script of MOFA2 for vertical integration (feature selection) for any matched multimodality data, such as RNA+ADT, RNA+ATAC, multiple RNA+ADT, multiple RNA+ATAC data types. 
# run script command for 3 batches of 2 modality (RNA+ADT) data 
# Rscript main_MOFA2_fs.Rmd  './rna1.h5' './rna2.h5' './rna3.h5' './adt1.h5' './adt2.h5' './adt3.h5' 3 2 './MOFA2/'
# run script command for 1 batches of 3 modality (RNA+ADT+ATAC) data 
# Rscript main_MOFA2_fs.Rmd  './rna.h5' './adt.h5' './atac.h5' 1 3 './MOFA2/'

# wrap the MOFA2 function
run_MOFA2 <- function(processed_data,  plot=FALSE){
    if (!is.null(processed_data$rna) & !is.null(processed_data$adt) & is.null(processed_data$atac)){
      data <- c(list(view_1 = processed_data$rna), list(view_2 = processed_data$adt))
      rownames(data$view_1) <- paste0("rna-", rownames(data$view_1) )
      rownames(data$view_2) <- paste0("adt-", rownames(data$view_2))}
    if (!is.null(processed_data$rna) & is.null(processed_data$adt) & !is.null(processed_data$atac)){
      data <- c(list(view_1 = processed_data$rna), list(view_2 = processed_data$atac))} 
    if (is.null(processed_data$rna) & !is.null(processed_data$adt) & !is.null(processed_data$atac)){
      data <- c(list(view_1 = processed_data$adt), list(view_2 = processed_data$atac))} 
    if (!is.null(processed_data$rna) & !is.null(processed_data$adt) & !is.null(processed_data$atac)){
      data <- c(list(view_1 = processed_data$rna), list(view_2 = processed_data$adt), list(view_3 = processed_data$atac))}
  
    new_colname <- make_unique_colnames(colnames(data[[1]]))
    for(view in names(data)) {
      colnames(data[[view]]) <- new_colname
    }

    groups <- processed_data$batch
    MOFAobject <- create_mofa_from_matrix(data, groups)
    MOFAobject <- create_mofa(data, groups=groups)
    data_opts <- get_default_data_options(MOFAobject)
    model_opts <- get_default_model_options(MOFAobject)
    train_opts <- get_default_training_options(MOFAobject)
    train_opts$seed <- 42
    train_opts$gpu_mode <- TRUE
    MOFAobject <- prepare_mofa(
      object = MOFAobject,
      data_options = data_opts,
      model_options = model_opts,
      training_options = train_opts
    )
    MOFAobject.trained <- run_mofa(MOFAobject, use_basilisk=FALSE) #TRUE)
    return (MOFAobject.trained)
}

# input data
args <- commandArgs(trailingOnly = TRUE)
batch_num <-  args[length(args)-2]
num <-  args[length(args)-1]
save_path <- args[length(args)]
print(num)
if (num==3){
  rna_path <- args[1:((length(args)-3)/3)] 
  adt_path <- args[((length(args)-3)/3+1):(2*(length(args)-3)/3)]
  atac_path <- args[(2*(length(args)-3)/3+1):(length(args)-3)]
}
if (num==2){
  rna_path <- args[1:((length(args)-3)/2)] 
  adt_path <- args[((length(args)-3)/2+1):(length(args)-3)]
  atac_path <- "NULL"
}
file_paths <- list(
  rna_path = rna_path,
  adt_path = adt_path,
  atac_path = atac_path
)
print(file_paths)
print(length(file_paths$atac_path))

# run methods
begin_time <- Sys.time()
if (atac_path[1]=="NULL"){  #if (atac_path[1]=="NULL"){ 
processed_data <- read_h5_data(file_paths$rna_path, file_paths$adt_path, NULL)
}else if (adt_path[1]=="NULL"){
processed_data <- read_h5_data(file_paths$rna_path, NULL, file_paths$atac_path)
}else if (rna_path[1]=="NULL"){
processed_data <- read_h5_data(NULL, file_paths$adt_path, file_paths$atac_path)
}else {
processed_data <- read_h5_data(file_paths$rna_path, file_paths$adt_path, file_paths$atac_path)
}
MOFAobject.trained <- run_MOFA2(processed_data, plot = FALSE)
embedding <-c()
for (i in c(1:batch_num)){
  embedding <- rbind(embedding, MOFAobject.trained@expectations$Z[[i]])
}
# feature selection
feature_score <- c()
for (i in c(1:length(MOFAobject.trained@intercepts))){
  feature_score <- c(feature_score, list(MOFAobject.trained@intercepts[[i]]$group1))
}
end_time <- Sys.time()
all_time <- difftime(end_time, begin_time, units="secs")

if (!dir.exists(save_path)) {
   dir.create(save_path, recursive = TRUE)
   print("path create")
}
 
#write_h5(exprs_list = list(rna = embedding), 
#              h5file_list = c(paste0(save_path,"embedding.h5")))
save(feature_score, file=c(paste0(save_path,"feature_score.RData")))
write.csv(all_time, paste0(save_path,"time.csv"))



