```{r}
library(glue)
library(rhdf5)
library(caret)
source("data_to_h5.R")
```

```{r}
seed5fold <- function(rna=NULL, adt=NULL, atac=NULL, cty=NULL, seedInput=1){
  set.seed(seedInput)
  f <- createFolds(cty, 10)

  folds_10 <- c(f[[1]])
  folds_30 <- c(f[[1]], f[[2]], f[[3]])
  folds_50 <- c(f[[1]], f[[2]], f[[3]], f[[4]], f[[5]])
  folds_80 <- c(f[[1]], f[[2]], f[[3]], f[[4]], f[[5]], f[[6]], f[[7]], f[[8]])
  
  rna_10 <- rna[, folds_10]
  rna_30 <- rna[, folds_30]
  rna_50 <- rna[, folds_50]
  rna_80 <- rna[, folds_80]
  
  if (!is.null(adt)){
    adt_10 <- adt[, folds_10]
    adt_30 <- adt[, folds_30]
    adt_50 <- adt[, folds_50]
    adt_80 <- adt[, folds_80]
  } else {
    adt_10 <- NULL
    adt_30 <- NULL
    adt_50 <- NULL
    adt_80 <- NULL
  }
  
  if (!is.null(atac)){
    atac_10 <- atac[, folds_10]
    atac_30 <- atac[, folds_30]
    atac_50 <- atac[, folds_50]
    atac_80 <- atac[, folds_80]
  } else {
    atac_10 <- NULL
    atac_30 <- NULL
    atac_50 <- NULL
    atac_80 <- NULL
  }
  
  cty_10 <- cty[folds_10]
  cty_30 <- cty[folds_30]
  cty_50 <- cty[folds_50]
  cty_80 <- cty[folds_80]

  return(list(rna_10 = rna_10, rna_30 = rna_30, rna_50 = rna_50, rna_80 = rna_80, adt_10 = adt_10, adt_30 = adt_30, adt_50 = adt_50, adt_80 = adt_80,atac_10 = atac_10, atac_30 = atac_30, atac_50 = atac_50, atac_80 = atac_80, cty_10 = cty_10, cty_30 = cty_30, cty_50 = cty_50, cty_80 = cty_80))
}
```

```{r}

rna <- h5read(glue("./rna.h5"), "matrix/data")
barcodes <- h5read(glue("./rna.h5"), "matrix/barcodes")
features <- h5read(glue("./rna.h5"), "matrix/features")
colnames(rna) <- features
rownames(rna) <- barcodes
rna <- t(rna) 

adt <- h5read(glue("./adt.h5"), "matrix/data")
barcodes <- h5read(glue("./adt.h5"), "matrix/barcodes")
features <- h5read(glue("./adt.h5"), "matrix/features")
colnames(adt) <- features
rownames(adt) <- barcodes
adt <- t(adt) 

cty <- read.csv(glue("./cty.csv"))$x

Result <- seed5fold(rna=rna, adt=adt, atac=NULL, cty=cty)
rna_10 <- Result$rna_10
rna_30 <- Result$rna_30 
rna_50 <- Result$rna_50
rna_80 <- Result$rna_80

adt_10 <- Result$adt_10
adt_30 <- Result$adt_30 
adt_50 <- Result$adt_50
adt_80 <- Result$adt_80

atac_10 <- Result$atac_10
atac_30 <- Result$atac_30 
atac_50 <- Result$atac_50
atac_80 <- Result$atac_80

cty_10 <- Result$cty_10
cty_30 <- Result$cty_30 
cty_50 <- Result$cty_50
cty_80 <- Result$cty_80


if (!is.null(rna_10)){
  write_h5_scJoint(exprs_list = list(rna = rna_10), h5file_list = c(glue("./rna_10.h5")))
  write_h5_scJoint(exprs_list = list(rna = rna_30), h5file_list = c(glue("./rna_30.h5")))
  write_h5_scJoint(exprs_list = list(rna = rna_50), h5file_list = c(glue("./rna_50.h5")))
  write_h5_scJoint(exprs_list = list(rna = rna_80), h5file_list = c(glue("./rna_80.h5")))
}

if (!is.null(adt_10)){
  write_h5_scJoint(exprs_list = list(rna = adt_10), h5file_list = c(glue("./adt_10.h5")))
  write_h5_scJoint(exprs_list = list(rna = adt_30), h5file_list = c(glue("./adt_30.h5")))
  write_h5_scJoint(exprs_list = list(rna = adt_50), h5file_list = c(glue("./adt_50.h5")))
  write_h5_scJoint(exprs_list = list(rna = adt_80), h5file_list = c(glue("./adt_80.h5")))
}

if (!is.null(atac_10)){
  write_h5_scJoint(exprs_list = list(rna = atac_10), h5file_list = c(glue("./atac_10.h5")))
  write_h5_scJoint(exprs_list = list(rna = atac_30), h5file_list = c(glue("./atac_30.h5")))
  write_h5_scJoint(exprs_list = list(rna = atac_50), h5file_list = c(glue("./atac_50.h5")))
  write_h5_scJoint(exprs_list = list(rna = atac_80), h5file_list = c(glue("./atac_80.h5")))
}
    
  write_csv_scJoint(cellType_list =  list(rna = cty_10), csv_list = c(glue("./cty_10.csv")))
  write_csv_scJoint(cellType_list =  list(rna = cty_30), csv_list = c(glue("./cty_30.csv")))
  write_csv_scJoint(cellType_list =  list(rna = cty_50), csv_list = c(glue("./cty_50.csv")))
  write_csv_scJoint(cellType_list =  list(rna = cty_80), csv_list = c(glue("./cty_80.csv")))

```

