#python main_sciPENN_classification.py --path1  "../../data/dataset_final/D51/rna1.h5"   --path2 "../../data/dataset_final/D51/adt1.h5" --label "../../data/dataset_final/D51/cty1.csv" --query_path1 "../../data/dataset_final/D51/rna2.h5" --query_path2 "../../data/dataset_final/D51/adt2.h5"  --query_label  "../../data/dataset_final/D51/cty2.csv"  --save_path "../../result/classification/D51/sciPENN_own/r2/"
#python main_sciPENN_classification.py --path1  "../../data/dataset_final/D51/rna2.h5"   --path2 "../../data/dataset_final/D51/adt2.h5" --label "../../data/dataset_final/D51/cty2.csv" --query_path1 "../../data/dataset_final/D51/rna1.h5" --query_path2 "../../data/dataset_final/D51/adt1.h5"  --query_label  "../../data/dataset_final/D51/cty1.csv"  --save_path "../../result/classification/D51/sciPENN_own/r1/"


#python main_sciPENN_classification.py --path1  "../../data/dataset_final/D53/rna1.h5"   --path2 "../../data/dataset_final/D53/adt1.h5" --label "../../data/dataset_final/D53/cty1.csv" --query_path1 "../../data/dataset_final/D53/rna2.h5" --query_path2 "../../data/dataset_final/D53/adt2.h5"  --query_label  "../../data/dataset_final/D53/cty2.csv"  --save_path "../../result/classification/D53/sciPENN_own/r2/"
#python main_sciPENN_classification.py --path1  "../../data/dataset_final/D53/rna2.h5"   --path2 "../../data/dataset_final/D53/adt2.h5" --label "../../data/dataset_final/D53/cty2.csv" --query_path1 "../../data/dataset_final/D53/rna1.h5" --query_path2 "../../data/dataset_final/D53/adt1.h5"  --query_label  "../../data/dataset_final/D53/cty1.csv"  --save_path "../../result/classification/D53/sciPENN_own/r1/"

#python main_sciPENN_classification.py --path1  "../../data/dataset_final/D55/rna1.h5"   --path2 "../../data/dataset_final/D55/adt1.h5" --label "../../data/dataset_final/D55/cty1.csv" --query_path1 "../../data/dataset_final/D55/rna2.h5" --query_path2 "../../data/dataset_final/D55/adt2.h5"  --query_label  "../../data/dataset_final/D55/cty2.csv"  --save_path "../../result/classification/D55/sciPENN_own/r2/"
#python main_sciPENN_classification.py --path1  "../../data/dataset_final/D55/rna2.h5"   --path2 "../../data/dataset_final/D55/adt2.h5" --label "../../data/dataset_final/D55/cty2.csv" --query_path1 "../../data/dataset_final/D55/rna1.h5" --query_path2 "../../data/dataset_final/D55/adt1.h5"  --query_label  "../../data/dataset_final/D55/cty1.csv"  --save_path "../../result/classification/D55/sciPENN_own/r1/"


python main_sciPENN_classification.py --path1  "../../data/dataset_final/D52/rna1.h5"   --path2 "../../data/dataset_final/D52/adt1.h5"  --label "../../data/dataset_final/D52/cty1.csv"   --query_path1  "../../data/dataset_final/D52/rna2.h5"  "../../data/dataset_final/D52/rna3.h5" --query_path2 "../../data/dataset_final/D52/adt2.h5" "../../data/dataset_final/D52/adt3.h5"  --query_label  "../../data/dataset_final/D52/cty2.csv" "../../data/dataset_final/D52/cty3.csv"  --save_path "../../result/classification/D52/sciPENN_own/r1/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/D52/rna2.h5"   --path2 "../../data/dataset_final/D52/adt2.h5"  --label "../../data/dataset_final/D52/cty2.csv"   --query_path1  "../../data/dataset_final/D52/rna1.h5"  "../../data/dataset_final/D52/rna3.h5" --query_path2 "../../data/dataset_final/D52/adt1.h5" "../../data/dataset_final/D52/adt3.h5"  --query_label  "../../data/dataset_final/D52/cty1.csv" "../../data/dataset_final/D52/cty3.csv"  --save_path "../../result/classification/D52/sciPENN_own/r2/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/D52/rna3.h5"   --path2 "../../data/dataset_final/D52/adt3.h5"  --label "../../data/dataset_final/D52/cty3.csv"   --query_path1  "../../data/dataset_final/D52/rna1.h5"  "../../data/dataset_final/D52/rna3.h5" --query_path2 "../../data/dataset_final/D52/adt1.h5" "../../data/dataset_final/D52/adt3.h5"  --query_label  "../../data/dataset_final/D52/cty1.csv" "../../data/dataset_final/D52/cty3.csv"  --save_path "../../result/classification/D52/sciPENN_own/r3/"





python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna1.h5"   --path2 "../../data/dataset_final/D54/adt1.h5"  --label "../../data/dataset_final/D54/cty1.csv"   --query_path1  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt2.h5" "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r1/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna2.h5"   --path2 "../../data/dataset_final/D54/adt2.h5"  --label "../../data/dataset_final/D54/cty2.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r2/"

python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna3.h5"   --path2 "../../data/dataset_final/D54/adt3.h5"  --label "../../data/dataset_final/D54/cty3.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r3/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna4.h5"   --path2 "../../data/dataset_final/D54/adt4.h5"  --label "../../data/dataset_final/D54/cty4.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r4/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna5.h5"   --path2 "../../data/dataset_final/D54/adt5.h5"  --label "../../data/dataset_final/D54/cty5.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r5/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna6.h5"   --path2 "../../data/dataset_final/D54/adt6.h5"  --label "../../data/dataset_final/D54/cty6.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r6/"

python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna7.h5"   --path2 "../../data/dataset_final/D54/adt7.h5"  --label "../../data/dataset_final/D54/cty7.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r7/"

python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna8.h5"   --path2 "../../data/dataset_final/D54/adt8.h5"  --label "../../data/dataset_final/D54/cty8.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r8/"

python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna9.h5"   --path2 "../../data/dataset_final/D54/adt9.h5"  --label "../../data/dataset_final/D54/cty9.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna10.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r9/"



python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna10.h5"   --path2 "../../data/dataset_final/D54/adt10.h5"  --label "../../data/dataset_final/D54/cty10.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna11.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt11.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty11.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r10/"

python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna11.h5"   --path2 "../../data/dataset_final/D54/adt11.h5"  --label "../../data/dataset_final/D54/cty11.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5" "../../data/dataset_final/D54/rna12.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt12.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty12.csv"  --save_path "../../result/classification/D54/sciPENN_own/r11/"

python main_sciPENN_classification.py --path1  "../../data/dataset_final/D54/rna12.h5"   --path2 "../../data/dataset_final/D54/adt12.h5"  --label "../../data/dataset_final/D54/cty12.csv"   --query_path1  "../../data/dataset_final/D54/rna1.h5"  "../../data/dataset_final/D54/rna2.h5"  "../../data/dataset_final/D54/rna3.h5"  "../../data/dataset_final/D54/rna4.h5"  "../../data/dataset_final/D54/rna5.h5"  "../../data/dataset_final/D54/rna6.h5"  "../../data/dataset_final/D54/rna7.h5"  "../../data/dataset_final/D54/rna8.h5"  "../../data/dataset_final/D54/rna9.h5"  "../../data/dataset_final/D54/rna10.h5" "../../data/dataset_final/D54/rna11.h5" --query_path2 "../../data/dataset_final/D54/adt1.h5" "../../data/dataset_final/D54/adt2.h5"  "../../data/dataset_final/D54/adt3.h5"  "../../data/dataset_final/D54/adt4.h5"  "../../data/dataset_final/D54/adt5.h5"  "../../data/dataset_final/D54/adt6.h5"  "../../data/dataset_final/D54/adt7.h5"  "../../data/dataset_final/D54/adt8.h5"  "../../data/dataset_final/D54/adt9.h5"  "../../data/dataset_final/D54/adt10.h5"  "../../data/dataset_final/D54/adt11.h5"  --query_label  "../../data/dataset_final/D54/cty1.csv" "../../data/dataset_final/D54/cty2.csv" "../../data/dataset_final/D54/cty3.csv" "../../data/dataset_final/D54/cty4.csv" "../../data/dataset_final/D54/cty5.csv" "../../data/dataset_final/D54/cty6.csv" "../../data/dataset_final/D54/cty7.csv" "../../data/dataset_final/D54/cty8.csv" "../../data/dataset_final/D54/cty9.csv" "../../data/dataset_final/D54/cty10.csv" "../../data/dataset_final/D54/cty11.csv"  --save_path "../../result/classification/D54/sciPENN_own/r12/"



python main_sciPENN_classification.py --path1  "../../data/dataset_final/SD15/rna1.h5"   --path2 "../../data/dataset_final/SD15/adt1.h5" --label "../../data/dataset_final/SD15/cty1.csv" --query_path1 "../../data/dataset_final/SD15/rna2.h5" --query_path2 "../../data/dataset_final/SD15/adt2.h5"  --query_label  "../../data/dataset_final/SD15/cty2.csv"  --save_path "../../result/classification/SD15/sciPENN_own/r2/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/SD15/rna2.h5"   --path2 "../../data/dataset_final/SD15/adt2.h5" --label "../../data/dataset_final/SD15/cty2.csv" --query_path1 "../../data/dataset_final/SD15/rna1.h5" --query_path2 "../../data/dataset_final/SD15/adt1.h5"  --query_label  "../../data/dataset_final/SD15/cty1.csv"  --save_path "../../result/classification/SD15/sciPENN_own/r1/"

python main_sciPENN_classification.py --path1  "../../data/dataset_final/SD16/rna1.h5"   --path2 "../../data/dataset_final/SD16/adt1.h5" --label "../../data/dataset_final/SD16/cty1.csv" --query_path1 "../../data/dataset_final/SD16/rna2.h5" --query_path2 "../../data/dataset_final/SD16/adt2.h5"  --query_label  "../../data/dataset_final/SD16/cty2.csv"  --save_path "../../result/classification/SD16/sciPENN_own/r2/"
python main_sciPENN_classification.py --path1  "../../data/dataset_final/SD16/rna2.h5"   --path2 "../../data/dataset_final/SD16/adt2.h5" --label "../../data/dataset_final/SD16/cty2.csv" --query_path1 "../../data/dataset_final/SD16/rna1.h5" --query_path2 "../../data/dataset_final/SD16/adt1.h5"  --query_label  "../../data/dataset_final/SD16/cty1.csv"  --save_path "../../result/classification/SD16/sciPENN_own/r1/"
















