
# for vertical integration, need to use the old versions
# devtools::install_github("welch-lab/liger", ref = "v1.0.1")
library(rhdf5)
library(scran)
library(Seurat)
library(rliger)
library(HDF5Array)

# The script of UINMF for cross integration. The output is joint embedding (dimension reduction)
# run commond for UINMF
# Rscript main_UINMF_cross.Rmd  '../../data/dataset_final/D55/rna1.h5' '../../data/dataset_final/D55/rna2.h5'  '../../data/dataset_final/D55/adt1.h5' '../../data/dataset_final/D55/adt2.h5' '../../result/embedding/diagonal integration/D55/UINMF/' 

write_h5 <- function(exprs_list, h5file_list) {
  if (length(unique(lapply(exprs_list, rownames))) != 1) {
    stop("rownames of exprs_list are not identical.")
  }
  
  for (i in seq_along(exprs_list)[1:(length(seq_along(exprs_list)))]) {
    if (file.exists(h5file_list[i])) {
      warning("h5file exists! will rewrite it.")
      system(paste("rm", h5file_list[i]))
    }
    
    h5createFile(h5file_list[i])
    #h5createGroup(h5file_list[i], "data")
    writeHDF5Array(((exprs_list[[i]])), h5file_list[i], name = "data")
    print(h5ls(h5file_list[i]))
  }
}


h5_to_matrix <- function(path){
    h5_data <- h5read(path,"matrix")
    feature <- h5_data$features
    barcode <- h5_data$barcodes
    data <- t(h5_data$data)
    colnames(data) <- as.character(barcode)
    rownames(data) <- as.character(feature)
    rownames(data) <- gsub("_", "-", rownames(data))
    return (data)
}

run_UINMF <- function(rna_path1, rna_path2, adt_path1, adt_path2, save_path){
  begin_time <- Sys.time()

  rna1 <- h5_to_matrix(rna_path1)
  rna2 <- h5_to_matrix(rna_path2)
  lig <- createLiger(list(rna1 = rna1, rna2 = rna2))
  lig <- normalize(lig) %>%
    selectGenes(useDatasets = "rna1", thresh = 0.1) %>%
    scaleNotCenter()
  
  adt1 <- h5_to_matrix(adt_path1)
  adt1 <- as(adt1, "CsparseMatrix")
  unshareNormed1 <- normalize(adt1)
  se1 <- CreateSeuratObject(unshareNormed1)
  se1 <- FindVariableFeatures(se1, selection.method = "vst", nfeatures = 2000)
  adt1_top2000 <- VariableFeatures(se1)
  unshareScaled1 <- scaleNotCenter(unshareNormed1[adt1_top2000,])
  varUnsharedFeatures(lig, "rna1") <- adt1_top2000
  scaleUnsharedData(lig, "rna1") <- unshareScaled1
  
  adt2 <- h5_to_matrix(adt_path2)
  adt2 <- as(adt2, "CsparseMatrix")
  unshareNormed2 <- normalize(adt2)
  adt2_top2000 <- VariableFeatures(se1)
  unshareScaled2 <- scaleNotCenter(unshareNormed2[adt2_top2000,])
  varUnsharedFeatures(lig, "rna2") <- adt2_top2000
  scaleUnsharedData(lig, "rna2") <- unshareScaled2
  
  lig <- runUINMF(lig, k = 30, nIteration = 30)
  lig <- quantileNorm(lig)
  
  result <- lig@H.norm
  end_time <- Sys.time()
  all_time <- difftime(end_time, begin_time, units="secs")
  
  if (!dir.exists(save_path)) {
    dir.create(save_path, recursive = TRUE)
    print("path create")
  }
  write_h5(exprs_list = list(rna = result), h5file_list = c(paste0(save_path,"embedding.h5")))
  write.csv(all_time, paste(save_path,"time.csv"))
}

# read parameters, the input is RNA counts and ATAC gene activity score counts
begin_time <- Sys.time()
args <- commandArgs(trailingOnly = TRUE)
rna_path1 <- args[1] 
rna_path2 <- args[2] 
adt_path1 <- args[3] 
adt_path2 <- args[4] 
save_path <- args[5] 
run_UINMF(rna_path1, rna_path2, adt_path1, adt_path2, save_path)
